library(readxl)
library(psych)
library(ggplot2)
a1<-read_excel("D:\\KIMS.xlsx")
dim(a1)
summary(a1)
describe(a1)
View(a1)
is.na(a1)
sum(is.na(a1))
###########sex
table(a1$sex)
pie(a1$sex)
a1$sex<-ifelse(a1$sex=="f","F",a1$sex)
table(a1$sex)
a1$sex<-ifelse(a1$sex=="m","M",a1$sex)
table(a1$sex)
a1$sex<-ifelse(a1$sex=="`F","F",a1$sex)
table(a1$sex)
a1$sex<-ifelse(a1$sex=="FALSE","F",a1$sex)
table(a1$sex)
###############weight
plot(a1$weight,type = "o",col="orange")
summary(a1$weight)
iqr<-11.72-7.10
ul<-11.72+(1.5*iqr)
ul
median(a1$weight)
a1$weight<-ifelse(a1$weight>18.65,median(a1$weight),a1$weight)
median(a1$weight)
summary(a1$weight)
###########age-in-months
barplot(table(a1$age_in_months))
median(a1$age_in_months)
summary(a1$age_in_months)
iqr1<-36.66-11
ul1<-36+(1.5*iqr)
ul1
a1$age_in_months<-ifelse(a1$age_in_months>42.93,median(a1$age_in_months),a1$age_in_months)
barplot(table(a1$age_in_months))
#######valve morphology
table(a1$Valve_Morphology)
#####leak
table(a1$leak)
######re-operation
table(a1$Re_operation)
